# train_betting_model_fixed.py
"""
FIXED Betting Model Trainer with proper historical odds integration
- Uses historical odds generated by historical_odds_fetcher.py
- Properly matches odds to games using multiple criteria
- Realistic backtesting with actual market prices
"""

import sqlite3
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import pickle
import os
import warnings
warnings.filterwarnings('ignore')

from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, roc_auc_score, log_loss
from sklearn.calibration import CalibratedClassifierCV, calibration_curve

DB_PATH   = r"E:/Bettr Bot/betting-bot/data/betting.db"
MODEL_DIR = r"E:/Bettr Bot/betting-bot/models/"

# Configurable parameters
PRICE_AGGREGATION = "median"   # "median" (conservative) or "best" (optimistic)
MIN_EDGE          = 0.025      # Increased from 0.03 to find more bets
MAX_BET_PCT       = 0.015      # Decreased to be more conservative
MIN_CONF          = 0.55       # Decreased slightly
MAX_DEC_ODDS_TO_BET   = 2.70    # skip longshots bigger than ~+170
MIN_ABS_PROB_TO_BET   = 0.54    # only bet a side if your model has ≥54% on that side
MIN_BOOKS_REQUIRED    = 3       # require consensus from at least 3 books
KELLY_FRACTION        = 0.10    # dial Kelly way down
# scale the edge requirement up for higher prices
ODDS_EDGE_BUMPS = [(2.2, 0.01), (2.4, 0.02), (2.6, 0.03)]

class FixedBettingTrainer:
    def __init__(self):
        self.conn = sqlite3.connect(DB_PATH)
        self.scaler = StandardScaler()
        self.feature_importance = {}
        self.model_metrics = {}
        self.uses_scaled = False
        self.team_name_map = {}
        self._init_team_map()

    def _table_exists(self, name: str) -> bool:
        try:
            return pd.read_sql_query(
                "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?",
                self.conn, params=[name]
            ).shape[0] > 0
        except Exception:
            return False

    def _init_team_map(self):
        ABBR_TO_FULL = {
            'ARI':'Arizona Cardinals','ATL':'Atlanta Falcons','BAL':'Baltimore Ravens','BUF':'Buffalo Bills',
            'CAR':'Carolina Panthers','CHI':'Chicago Bears','CIN':'Cincinnati Bengals','CLE':'Cleveland Browns',
            'DAL':'Dallas Cowboys','DEN':'Denver Broncos','DET':'Detroit Lions','GB':'Green Bay Packers',
            'HOU':'Houston Texans','IND':'Indianapolis Colts','JAX':'Jacksonville Jaguars','KC':'Kansas City Chiefs',
            'LV':'Las Vegas Raiders','LAC':'Los Angeles Chargers','LAR':'Los Angeles Rams','MIA':'Miami Dolphins',
            'MIN':'Minnesota Vikings','NE':'New England Patriots','NO':'New Orleans Saints','NYG':'New York Giants',
            'NYJ':'New York Jets','PHI':'Philadelphia Eagles','PIT':'Pittsburgh Steelers','SF':'San Francisco 49ers',
            'SEA':'Seattle Seahawks','TB':'Tampa Bay Buccaneers','TEN':'Tennessee Titans','WAS':'Washington Commanders'
        }
        m = {}
        for abbr, full in ABBR_TO_FULL.items():
            m[abbr] = abbr
            m[full] = abbr
            m[full.upper()] = abbr
            m[full.lower()] = abbr
        m.update({
            'LA':'LAR','Los Angeles':'LAR','Las Vegas':'LV','Oakland':'LV','Washington':'WAS',
            'Washington Redskins':'WAS','San Francisco':'SF','Green Bay':'GB','Kansas City':'KC',
            'New England':'NE','New York Giants':'NYG','New York Jets':'NYJ','Tampa Bay':'TB','New Orleans':'NO'
        })
        self.team_name_map = m

    def _normalize_team(self, name):
        if name is None: return None
        s = str(name).strip()
        if s in self.team_name_map: return self.team_name_map[s]
        if s.upper() in self.team_name_map: return self.team_name_map[s.upper()]
        if len(s) <= 3: return s.upper()
        for k, ab in self.team_name_map.items():
            if s.lower() in k.lower() or k.lower() in s.lower():
                return ab
        return s[:3].upper()

    def build_core_dataset(self):
        print("Building core dataset with verified features...")
        q = """
        SELECT 
            g.game_id, g.home_team, g.away_team,
            g.home_score, g.away_score, g.game_date,
            CASE WHEN g.home_score > g.away_score THEN 1 ELSE 0 END AS home_win,
            CAST(strftime('%Y', g.game_date) AS INTEGER) AS season,
            CAST(strftime('%m', g.game_date) AS INTEGER) AS month,
            CAST(strftime('%w', g.game_date) AS INTEGER) AS day_of_week
        FROM games g
        WHERE g.home_score IS NOT NULL AND g.away_score IS NOT NULL
          AND g.game_date > date('now', '-3 years')
        ORDER BY g.game_date
        """
        df = pd.read_sql_query(q, self.conn)
        print(f"Base dataset: {len(df)} games")
        if len(df) < 100:
            raise RuntimeError("Too little data.")

        df = self._ensure_pre_game_team_metrics(df)
        df = self._add_simple_momentum(df)
        df = self._add_matchup_features(df)
        df = self._add_rest_features(df)

        print(f"Final dataset: {len(df)} games, {len(df.columns)} features")
        return df

    # Train only on data BEFORE the test period
    def proper_time_split(self, df):
        df_sorted = df.sort_values('game_date')
        # Use 80% for training, 20% for testing
        # But ensure NO data leakage from future to past
        split_date = df_sorted['game_date'].quantile(0.8)
        train = df_sorted[df_sorted['game_date'] < split_date]
        test = df_sorted[df_sorted['game_date'] >= split_date]
        return train, test

    # Add this diagnostic to your trainer:
    def audit_odds_quality(self):
        matched = self.match_odds_to_games(self.df)
        print(f"Games with odds: {matched['actual_game_id'].nunique()}")
        print(f"Average books per game: {matched.groupby('actual_game_id')['sportsbook'].nunique().mean():.1f}")
        print(f"Odds range: {matched['odds'].min():.0f} to {matched['odds'].max():.0f}")
        
        # Check for unrealistic patterns
        if matched['odds'].min() > -200 and matched['odds'].max() < 200:
            print("WARNING: Odds range too narrow - likely simulated data")

    def _ensure_pre_game_team_metrics(self, df):
        df = df.sort_values('game_date').copy()
        for side in ('home','away'):
            wpct_pre = []; pf_pre = []; pa_pre = []; pd_pre = []
            totals = {}
            for _, r in df.iterrows():
                t = self._normalize_team(r[f'{side}_team'])
                if t not in totals:
                    totals[t] = {'gp':0,'w':0,'pf_sum':0.0,'pa_sum':0.0}
                cur = totals[t]; gp = cur['gp']
                pfm = cur['pf_sum']/gp if gp>0 else 20.0
                pam = cur['pa_sum']/gp if gp>0 else 20.0
                wpct_pre.append((cur['w']/gp) if gp>0 else 0.5)
                pf_pre.append(pfm); pa_pre.append(pam); pd_pre.append(pfm-pam)
                pf = float(r['home_score'] if side=='home' else r['away_score'])
                pa = float(r['away_score'] if side=='home' else r['home_score'])
                win = 1 if pf > pa else 0
                cur['gp'] += 1; cur['w'] += win; cur['pf_sum'] += pf; cur['pa_sum'] += pa
            df[f'{side}_wpct_pre'] = wpct_pre
            df[f'{side}_pf_pre']   = pf_pre
            df[f'{side}_pa_pre']   = pa_pre
            df[f'{side}_pd_pre']   = pd_pre
        return df

    def _add_simple_momentum(self, df):
        print("Adding momentum features...")
        df['home_form'] = 0.5; df['home_streak'] = 0
        df['away_form'] = 0.5; df['away_streak'] = 0

        team_records = {}
        all_teams = pd.concat([df['home_team'], df['away_team']]).astype(str).unique()
        for team in all_teams:
            q = """
            SELECT game_date,
                   CASE WHEN home_team = ? THEN 
                        CASE WHEN home_score > away_score THEN 1 ELSE 0 END
                   ELSE CASE WHEN away_score > home_score THEN 1 ELSE 0 END
                   END as won
            FROM games 
            WHERE (home_team = ? OR away_team = ?)
              AND home_score IS NOT NULL AND away_score IS NOT NULL
            ORDER BY game_date DESC
            """
            try:
                tg = pd.read_sql_query(q, self.conn, params=[team, team, team])
                tg['game_date'] = pd.to_datetime(tg['game_date'])
                team_records[team] = tg
            except:
                team_records[team] = pd.DataFrame(columns=['game_date','won'])

        for i, r in df.iterrows():
            if i % 200 == 0:
                print(f"  Processing momentum for game {i}/{len(df)}")
            gd = pd.to_datetime(r['game_date'])
            for side in ('home','away'):
                t = str(r[f'{side}_team'])
                rec = team_records.get(t)
                if rec is not None and not rec.empty:
                    recent = rec[rec['game_date'] < gd].head(5)
                    if len(recent) >= 2:
                        form = float(recent['won'].mean())
                        streak = 0
                        if len(recent) > 0:
                            last = int(recent['won'].iloc[0])
                            for w in recent['won']:
                                if int(w) == last: streak += 1
                                else: break
                            if last == 0: streak = -streak
                    else:
                        form, streak = 0.5, 0
                else:
                    form, streak = 0.5, 0
                df.at[i, f'{side}_form'] = form
                df.at[i, f'{side}_streak'] = streak
        return df

    def _add_matchup_features(self, df):
        print("Adding matchup features...")
        divisions = {
            'AFC_EAST':['BUF','MIA','NE','NYJ'],'AFC_NORTH':['BAL','CIN','CLE','PIT'],
            'AFC_SOUTH':['HOU','IND','JAX','TEN'],'AFC_WEST':['DEN','KC','LV','LAC'],
            'NFC_EAST':['DAL','NYG','PHI','WAS'],'NFC_NORTH':['CHI','DET','GB','MIN'],
            'NFC_SOUTH':['ATL','CAR','NO','TB'],'NFC_WEST':['ARI','LAR','SF','SEA']
        }
        t2d = {}
        for d, teams in divisions.items():
            for t in teams:
                t2d[t] = d; t2d[self._normalize_team(t)] = d

        df['same_division'] = df.apply(
            lambda r: 1 if t2d.get(self._normalize_team(r['home_team'])) ==
                           t2d.get(self._normalize_team(r['away_team'])) else 0, axis=1)
        df['same_conference'] = df.apply(
            lambda r: 1 if (t2d.get(self._normalize_team(r['home_team']), '')[:3] ==
                            t2d.get(self._normalize_team(r['away_team']), '')[:3]) else 0, axis=1)
        return df

    def _add_rest_features(self, df):
        df = df.sort_values('game_date').copy()
        last_played = {}; home_rest=[]; away_rest=[]
        for _, r in df.iterrows():
            gd = pd.to_datetime(r['game_date'])
            ht = self._normalize_team(r['home_team'])
            at = self._normalize_team(r['away_team'])
            hr = (gd - last_played[ht]).days if ht in last_played else 7
            ar = (gd - last_played[at]).days if at in last_played else 7
            home_rest.append(hr); away_rest.append(ar)
            last_played[ht] = gd; last_played[at] = gd
        df['home_rest_days'] = home_rest
        df['away_rest_days'] = away_rest
        df['rest_diff'] = df['home_rest_days'] - df['away_rest_days']
        return df

    def engineer_core_features(self, df):
        print("Engineering core features...")
        df = df.fillna(0)
        df['home_power_pre'] = df['home_pd_pre']
        df['away_power_pre'] = df['away_pd_pre']
        df['power_diff']   = df['home_power_pre'] - df['away_power_pre']
        df['win_pct_diff'] = df['home_wpct_pre']  - df['away_wpct_pre']
        df['offense_diff'] = df['home_pf_pre']   - df['away_pf_pre']
        df['home_def_str'] = -df['home_pa_pre']
        df['away_def_str'] = -df['away_pa_pre']
        df['defense_diff'] = df['home_def_str'] - df['away_def_str']
        if 'home_form' in df.columns:
            df['form_diff'] = df['home_form'] - df['away_form']
            df['streak_diff'] = df['home_streak'] - df['away_streak']
        df['home_field_advantage'] = 2.5
        df['late_season'] = (df['month'] >= 11).astype(int)
        df['prime_time'] = ((df['day_of_week'] == 0) | (df['day_of_week'] == 1)).astype(int)
        df['both_good'] = ((df['home_power_pre'] > 2) & (df['away_power_pre'] > 2)).astype(int)
        df['mismatch_game'] = (abs(df['power_diff']) > 5).astype(int)
        df['power_x_form'] = df['power_diff'] * df.get('form_diff', 0)
        df['strength_disparity'] = abs(df['home_power_pre'] - df['away_power_pre'])
        return df

    def select_core_features(self, df):
        drop = ['game_id','home_team','away_team','home_score','away_score','game_date','season','home_win']
        feats = [c for c in df.columns if c not in drop]
        for c in feats:
            df[c] = pd.to_numeric(df[c], errors='coerce')
        df[feats] = df[feats].fillna(0)
        feats = [c for c in feats if df[c].nunique() > 1]
        print(f"Selected {len(feats)} features for training")
        print("Key features:", [c for c in feats if ('diff' in c or 'power' in c)][:10])
        return feats

    def train_calibrated_models(self, df):
        print("Training calibrated models...")
        feats = self.select_core_features(df)
        d = df.sort_values('game_date').reset_index(drop=True)
        seasons = sorted(d['season'].dropna().unique().tolist())

        use_season = len(seasons) >= 3
        if use_season:
            train_mask = d['season'].isin(seasons[:-2])
            cal_mask   = d['season'].isin([seasons[-2]])
            test_mask  = d['season'].isin([seasons[-1]])
            if d.loc[test_mask].shape[0] < 100:
                use_season = False
        if not use_season:
            n = len(d); train_end = int(n*0.6); cal_end = int(n*0.8)
            train_mask = d.index < train_end
            cal_mask   = (d.index >= train_end) & (d.index < cal_end)
            test_mask  = d.index >= cal_end

        X_train, y_train = d.loc[train_mask, feats], d.loc[train_mask, 'home_win']
        X_cal,   y_cal   = d.loc[cal_mask, feats],   d.loc[cal_mask, 'home_win']
        X_test,  y_test  = d.loc[test_mask, feats],  d.loc[test_mask, 'home_win']

        print(f"Train: {len(X_train)}, Cal: {len(X_cal)}, Test: {len(X_test)}")

        models = {
            'LogisticRegression': LogisticRegression(C=0.5, max_iter=1000, random_state=42),
            'RandomForest': RandomForestClassifier(
                n_estimators=250, max_depth=8, min_samples_split=40, min_samples_leaf=12, random_state=42)
        }

        results = {}; best = -1e9
        X_tr_s = self.scaler.fit_transform(X_train)
        X_ca_s = self.scaler.transform(X_cal)
        X_te_s = self.scaler.transform(X_test)

        for name, base in models.items():
            print(f"\nTraining {name}...")
            if name == 'LogisticRegression':
                base.fit(X_tr_s, y_train)
                calibrated = CalibratedClassifierCV(base, method='sigmoid', cv='prefit')
                calibrated.fit(X_ca_s, y_cal)
                proba = calibrated.predict_proba(X_te_s)[:,1]
                uses_scaled = True
            else:
                base.fit(X_train, y_train)
                calibrated = CalibratedClassifierCV(base, method='sigmoid', cv='prefit')
                calibrated.fit(X_cal, y_cal)
                proba = calibrated.predict_proba(X_test)[:,1]
                uses_scaled = False

            pred = (proba > 0.5).astype(int)
            acc = accuracy_score(y_test, pred)
            auc = roc_auc_score(y_test, proba)
            ll  = log_loss(y_test, proba)
            pt, pp = calibration_curve(y_test, proba, n_bins=5)
            cal_err = float(np.mean(np.abs(pt - pp)))
            score = auc - 2*cal_err - 0.5*ll

            results[name] = {'model': calibrated,'accuracy':acc,'auc':auc,'logloss':ll,
                             'calibration_error':cal_err,'betting_score':score}
            print(f"  Accuracy: {acc:.3f}")
            print(f"  AUC: {auc:.3f}")
            print(f"  LogLoss: {ll:.3f}")
            print(f"  Calibration Error: {cal_err:.3f}")
            print(f"  Betting Score: {score:.3f}")

            if score > best:
                best = score
                self.best_model = calibrated
                self.feature_cols = feats
                self.uses_scaled = uses_scaled

            if hasattr(base, 'feature_importances_'):
                imp = (pd.DataFrame({'feature': feats, 'importance': base.feature_importances_})
                         .sort_values('importance', ascending=False))
                self.feature_importance[name] = imp
                print("\nTop 5 features for RandomForest:")
                print(imp.head())

        if not hasattr(self, 'best_model'):
            raise RuntimeError("No models trained successfully!")
        self.model_metrics = results
        print(f"\nBest model selected with betting score: {best:.3f}")
        return results

    def test_predictions(self, df):
        print("\nTesting prediction quality...")
        X_test = df.sort_values('game_date').tail(50)[self.feature_cols]
        if self.uses_scaled:
            p = self.best_model.predict_proba(self.scaler.transform(X_test))[:,1]
        else:
            p = self.best_model.predict_proba(X_test)[:,1]
        unique = len(np.unique(np.round(p, 2)))
        rng = p.max() - p.min()
        print(f"Unique prediction values: {unique}")
        print(f"Prediction range: {p.min():.3f} to {p.max():.3f}")
        print(f"Sample predictions: {p[:5]}")
        if unique < 5: print("WARNING: too few unique predictions!")
        if rng < 0.1: print("WARNING: prediction range narrow!")
        return p

    def match_odds_to_games(self, df):
        """
        Enhanced odds matching that handles multiple game_id formats
        and team name variations
        """
        print("Matching odds to games...")

        odds_query = """
        SELECT 
            o.game_id as odds_game_id,
            o.sportsbook,
            o.team,
            o.market,
            o.odds,
            o.timestamp
        FROM odds o
        WHERE LOWER(o.market) IN ('h2h', 'moneyline', 'ml')
        """

        try:
            odds_df = pd.read_sql_query(odds_query, self.conn)
            print(f"Loaded {len(odds_df)} odds records")

            if odds_df.empty:
                print("No odds found in database!")
                return pd.DataFrame()

            # Normalize team names in odds
            odds_df['team_norm'] = odds_df['team'].apply(self._normalize_team)

            # Convert timestamps
            odds_df['timestamp'] = pd.to_datetime(odds_df['timestamp'], errors='coerce')

            # Create multiple matching strategies
            matched_odds = []

            for _, game in df.iterrows():
                game_date = pd.to_datetime(game['game_date'])
                home_norm = self._normalize_team(game['home_team'])
                away_norm = self._normalize_team(game['away_team'])

                # Strategy 1: Direct game_id match
                direct_match = odds_df[odds_df['odds_game_id'] == game['game_id']]

                # Strategy 2: Date + team match (for generated odds)
                date_str = game_date.strftime('%Y-%m-%d')
                generated_id_patterns = [
                    f"{date_str}_{game['home_team']}_{game['away_team']}",
                    f"{game_date.date()}_{game['home_team']}_{game['away_team']}",
                ]

                team_match = odds_df[
                    (odds_df['odds_game_id'].isin(generated_id_patterns)) |
                    ((odds_df['team_norm'].isin([home_norm, away_norm])) &
                    (odds_df['timestamp'].dt.date == game_date.date()))
                ]

                # Combine matches
                game_odds = pd.concat([direct_match, team_match]).drop_duplicates()

                if not game_odds.empty:
                    # Filter to pre-game odds only (<= assumed kickoff)
                    kickoff_time = game_date + pd.Timedelta(hours=20)  # heuristic
                    pre_game_odds = game_odds[
                        (game_odds['timestamp'].notna()) &
                        (game_odds['timestamp'] <= kickoff_time)
                    ]

                    if not pre_game_odds.empty:
                        pre_game_odds = pre_game_odds.copy()
                        pre_game_odds['actual_game_id'] = game['game_id']
                        pre_game_odds['game_date'] = game['game_date']
                        pre_game_odds['home_team'] = game['home_team']
                        pre_game_odds['away_team'] = game['away_team']
                        pre_game_odds['home_win'] = game['home_win']

                        matched_odds.append(pre_game_odds)

            if matched_odds:
                all_odds = pd.concat(matched_odds, ignore_index=True)
                print(f"Successfully matched {len(all_odds)} odds records to {all_odds['actual_game_id'].nunique()} games")
                return all_odds

            print("No odds could be matched to games")
            return pd.DataFrame()

        except Exception as e:
            print(f"Error matching odds: {e}")
            return pd.DataFrame()

            """
            Enhanced odds matching that handles multiple game_id formats
            and team name variations
            """
            print("Matching odds to games...")
            
            # Get all odds from database
            odds_query = """
            SELECT 
                o.game_id as odds_game_id,
                o.sportsbook,
                o.team,
                o.market,
                o.odds,
                o.timestamp
            FROM odds o
            WHERE LOWER(o.market) IN ('h2h', 'moneyline', 'ml')
            """
            
            try:
                odds_df = pd.read_sql_query(odds_query, self.conn)
                print(f"Loaded {len(odds_df)} odds records")
                
                if odds_df.empty:
                    print("No odds found in database!")
                    return pd.DataFrame()
                
                # Normalize team names in odds
                odds_df['team_norm'] = odds_df['team'].apply(self._normalize_team)
                
                # Convert timestamps
                odds_df['timestamp'] = pd.to_datetime(odds_df['timestamp'], errors='coerce')
                
                # Create multiple matching strategies
                matched_odds = []
                
                for _, game in df.iterrows():
                    game_date = pd.to_datetime(game['game_date'])
                    home_norm = self._normalize_team(game['home_team'])
                    away_norm = self._normalize_team(game['away_team'])
                    
                    # Strategy 1: Direct game_id match
                    direct_match = odds_df[odds_df['odds_game_id'] == game['game_id']]
                    
                    # Strategy 2: Date + team match (for generated odds)
                    date_str = game_date.strftime('%Y-%m-%d')
                    generated_id_patterns = [
                        f"{date_str}_{game['home_team']}_{game['away_team']}",
                        f"{game_date.date()}_{game['home_team']}_{game['away_team']}"
                    ]
                    
                    team_match = odds_df[
                        (odds_df['odds_game_id'].isin(generated_id_patterns)) |
                        ((odds_df['team_norm'].isin([home_norm, away_norm])) & 
                        (odds_df['timestamp'].dt.date == game_date.date()))
                    ]
                    
                    # Combine matches
                    game_odds = pd.concat([direct_match, team_match]).drop_duplicates()
                    
                    if not game_odds.empty:
                        # Filter to pre-game odds only
                        kickoff_time = game_date + pd.Timedelta(hours=20)  # Assume evening games
                        pre_game_odds = game_odds[
                            (game_odds['timestamp'].notna()) & 
                            (game_odds['timestamp'] <= kickoff_time)
                        ]
                        
                        if not pre_game_odds.empty:
                            # Add game info to odds
                            pre_game_odds = pre_game_odds.copy()
                            pre_game_odds['actual_game_id'] = game['game_id']
                            pre_game_odds['game_date'] = game['game_date']
                            pre_game_odds['home_team'] = game['home_team']
                            pre_game_odds['away_team'] = game['away_team']
                            pre_game_odds['home_win'] = game['home_win']
                            
                            matched_odds.append(pre_game_odds)
                
                if matched_odds:
                    all_odds = pd.concat(matched_odds, ignore_index=True)
                    print(f"Successfully matched {len(all_odds)} odds records to {all_odds['actual_game_id'].nunique()} games")
                    return all_odds
                else:
                    print("No odds could be matched to games")
                    return pd.DataFrame()
                    
            except Exception as e:
                print(f"Error matching odds: {e}")
                return pd.DataFrame()

    def backtest_with_real_odds(self, df):
        """
        Enhanced backtest using properly matched historical odds
        """
        print("\nRunning REALISTIC backtest with matched odds...")

        # Get matched odds
        matched_odds = self.match_odds_to_games(df)

        if matched_odds.empty:
            print("No matched odds available - falling back to simulated backtest")
            return self.backtest_realistic(df)

        # Split data chronologically
        d = df.sort_values('game_date').reset_index(drop=True)
        test_start = int(len(d) * 0.8)
        test_games = d.iloc[test_start:].copy()

        print(f"Testing on {len(test_games)} games...")

        # Get odds for test games only
        test_odds = matched_odds[
            matched_odds['actual_game_id'].isin(test_games['game_id'])
        ].copy()

        if test_odds.empty:
            print("No odds for test games - using fallback")
            return self.backtest_realistic(df)

        print(f"Found odds for {test_odds['actual_game_id'].nunique()} test games")

        # Aggregate odds per game/team (median across books)
        def process_game_odds(game_odds):
            """Process odds for a single game"""
            agg_odds = []

            for team_norm in game_odds['team_norm'].unique():
                team_odds = game_odds[game_odds['team_norm'] == team_norm]

                # Take last price from each book before kickoff
                last_per_book = team_odds.sort_values('timestamp').groupby('sportsbook').tail(1)
                books = last_per_book['sportsbook'].nunique()

                last_per_book = last_per_book.copy()
                last_per_book['decimal_odds'] = last_per_book['odds'].apply(self._to_decimal_odds)
                last_per_book['implied_prob'] = 1.0 / last_per_book['decimal_odds']

                median_implied = last_per_book['implied_prob'].median()
                median_decimal = 1.0 / median_implied

                agg_odds.append({
                    'team_norm': team_norm,
                    'decimal_odds': median_decimal,
                    'implied_prob': median_implied,
                    'books': books
                })

            return agg_odds

        # Process all game odds
        game_odds_processed = {}
        for game_id, game_odds in test_odds.groupby('actual_game_id'):
            game_odds_processed[game_id] = process_game_odds(game_odds)

        # Run backtest
        bankroll = 1000.0
        initial_bankroll = bankroll
        total_staked = 0.0
        bets = wins = 0
        pnl = 0.0
        bet_log = []

        for _, game in test_games.iterrows():
            game_id = game['game_id']
            if game_id not in game_odds_processed:
                continue

            # Get model prediction
            x = game[self.feature_cols].values.reshape(1, -1)
            if self.uses_scaled:
                x = self.scaler.transform(x)
            p_home = float(self.best_model.predict_proba(x)[0, 1])
            p_away = 1.0 - p_home

            # Get market odds (expect exactly two sides aggregated)
            odds_data = game_odds_processed[game_id]
            if len(odds_data) != 2:
                continue

            # Map odds to home/away by normalized team code
            home_norm = self._normalize_team(game['home_team'])
            away_norm = self._normalize_team(game['away_team'])

            home_odds = next((o for o in odds_data if o['team_norm'] == home_norm), None)
            away_odds = next((o for o in odds_data if o['team_norm'] == away_norm), None)
            if not home_odds or not away_odds:
                continue

            # Remove vig (normalize the two implied probabilities)
            total_implied = home_odds['implied_prob'] + away_odds['implied_prob']
            mkt_home_prob = home_odds['implied_prob'] / total_implied
            mkt_away_prob = away_odds['implied_prob'] / total_implied

            # Utility for odds-dependent edge bump
            def edge_bump(od):
                bump = 0.0
                for thr, inc in ODDS_EDGE_BUMPS:
                    if od >= thr:
                        bump = inc
                return bump

            candidates = []

            # Evaluate HOME
            if (home_odds['decimal_odds'] <= MAX_DEC_ODDS_TO_BET and
                home_odds.get('books', 1) >= MIN_BOOKS_REQUIRED and
                p_home >= MIN_ABS_PROB_TO_BET):
                e_home = p_home - mkt_home_prob
                if e_home >= MIN_EDGE + edge_bump(home_odds['decimal_odds']):
                    candidates.append(('home', p_home, e_home, home_odds))

            # Evaluate AWAY
            if (away_odds['decimal_odds'] <= MAX_DEC_ODDS_TO_BET and
                away_odds.get('books', 1) >= MIN_BOOKS_REQUIRED and
                p_away >= MIN_ABS_PROB_TO_BET):
                e_away = p_away - mkt_away_prob
                if e_away >= MIN_EDGE + edge_bump(away_odds['decimal_odds']):
                    candidates.append(('away', p_away, e_away, away_odds))

            if not candidates:
                continue

            # Take the larger edge among qualified sides
            bet_team, win_prob, edge, odds_obj = max(candidates, key=lambda t: t[2])
            odds_value = odds_obj['decimal_odds']
            won = (game['home_win'] == 1) if bet_team == 'home' else (game['home_win'] == 0)

            # Define values used in logging
            confidence = self.generate_confidence_score(win_prob)
            max_edge = edge

            # Conservative Kelly with caps
            kelly_size = self.kelly_bet_size(win_prob, odds_value)
            bet_size = min(
                MAX_BET_PCT * bankroll,
                kelly_size * bankroll * KELLY_FRACTION,
                30.0,  # tighter per-bet cap
            )

            # Skip dust bets
            if bet_size <= 0:
                continue

            # Place bet
            profit = bet_size * (odds_value - 1.0) if won else -bet_size
            bankroll += profit
            pnl += profit
            total_staked += bet_size
            bets += 1
            wins += int(won)

            bet_log.append({
                'game_date': str(game['game_date']),
                'matchup': f"{game['away_team']} @ {game['home_team']}",
                'bet_team': bet_team,
                'bet_size': float(bet_size),
                'odds': float(odds_value),
                'edge': float(max_edge),
                'confidence': float(confidence),
                'won': bool(won),
                'profit': float(profit),
            })

        # Display results
        if bets > 0:
            win_rate = wins / bets
            roi = (pnl / total_staked) * 100 if total_staked > 0 else 0.0

            print("\nREALISTIC Backtest Results (with real odds):")
            print(f"  Games with odds: {len(game_odds_processed)}")
            print(f"  Bets placed: {bets}")
            print(f"  Total staked: ${total_staked:.2f}")
            print(f"  Win rate: {win_rate:.1%}")
            print(f"  Total P&L: ${pnl:.2f}")
            print(f"  ROI on staked: {roi:.1f}%")
            print(f"  Final bankroll: ${bankroll:.2f}")

            # breakdown
            fav = sum(1 for b in bet_log if b['odds'] < 2.0)
            dogs = bets - fav
            avg_odds = float(np.mean([b['odds'] for b in bet_log])) if bet_log else 0.0
            avg_edge = float(np.mean([b['edge'] for b in bet_log])) if bet_log else 0.0
            print(f"  Bets split: favorites {fav} / dogs {dogs}")
            print(f"  Avg price: {avg_odds:.2f}, Avg edge: {avg_edge:.3f}")

            # Show sample bets
            if bet_log:
                print(f"\nSample bets:")
                for bet in bet_log[:5]:
                    result = "WIN" if bet['won'] else "LOSS"
                    print(f"  {bet['game_date'][:10]} {bet['matchup'][:35]:<35} "
                        f"{bet['bet_team'].upper():<4} @{bet['odds']:.2f} "
                        f"${bet['bet_size']:.0f} {result}")
        else:
            print("No qualifying bets found with current parameters")
            print(f"Try reducing MIN_EDGE ({MIN_EDGE}) or MIN_CONF ({MIN_CONF})")

            """
            Enhanced backtest using properly matched historical odds
            """
            print("\nRunning REALISTIC backtest with matched odds...")
            
            # Get matched odds
            matched_odds = self.match_odds_to_games(df)
            
            if matched_odds.empty:
                print("No matched odds available - falling back to simulated backtest")
                return self.backtest_realistic(df)
            
            # Split data chronologically
            d = df.sort_values('game_date').reset_index(drop=True)
            test_start = int(len(d) * 0.8)
            test_games = d.iloc[test_start:].copy()
            
            print(f"Testing on {len(test_games)} games...")
            
            # Get odds for test games only
            test_odds = matched_odds[
                matched_odds['actual_game_id'].isin(test_games['game_id'])
            ].copy()
            
            if test_odds.empty:
                print("No odds for test games - using fallback")
                return self.backtest_realistic(df)
            
            print(f"Found odds for {test_odds['actual_game_id'].nunique()} test games")
            
            # Aggregate odds per game/team (median across books)
            def process_game_odds(game_odds):
                """Process odds for a single game"""
                agg_odds = []
                
                for team_norm in game_odds['team_norm'].unique():
                    team_odds = game_odds[game_odds['team_norm'] == team_norm]
                    
                    # Take last price from each book before kickoff
                    last_per_book = team_odds.sort_values('timestamp').groupby('sportsbook').tail(1)
                    books = last_per_book['sportsbook'].nunique()

                    last_per_book = last_per_book.copy()
                    last_per_book['decimal_odds'] = last_per_book['odds'].apply(self._to_decimal_odds)
                    last_per_book['implied_prob'] = 1.0 / last_per_book['decimal_odds']

                    median_implied = last_per_book['implied_prob'].median()
                    median_decimal = 1.0 / median_implied

                    agg_odds.append({
                        'team_norm': team_norm,
                        'decimal_odds': median_decimal,
                        'implied_prob': median_implied,
                        'books': books
                    })

                return agg_odds
            
            # Process all game odds
            game_odds_processed = {}
            for game_id, game_odds in test_odds.groupby('actual_game_id'):
                game_odds_processed[game_id] = process_game_odds(game_odds)
            
            # Run backtest
            bankroll = 1000.0
            initial_bankroll = bankroll
            bets = wins = 0
            pnl = 0.0
            bet_log = []
            
            for _, game in test_games.iterrows():
                game_id = game['game_id']
                
                if game_id not in game_odds_processed:
                    continue
                
                # Get model prediction
                x = game[self.feature_cols].values.reshape(1, -1)
                if self.uses_scaled:
                    x = self.scaler.transform(x)
                p_home = float(self.best_model.predict_proba(x)[0, 1])
                p_away = 1.0 - p_home
                
                # Get market odds
                odds_data = game_odds_processed[game_id]
                if len(odds_data) != 2:
                    continue
                
                # Map odds to home/away
                home_norm = self._normalize_team(game['home_team'])
                away_norm = self._normalize_team(game['away_team'])
                
                home_odds = away_odds = None
                for odds in odds_data:
                    if odds['team_norm'] == home_norm:
                        home_odds = odds
                    elif odds['team_norm'] == away_norm:
                        away_odds = odds
                
                if not home_odds or not away_odds:
                    continue
                
                # Remove vig by normalizing implied probabilities
                # Remove vig as you already do
                total_implied = home_odds['implied_prob'] + away_odds['implied_prob']
                mkt_home_prob = home_odds['implied_prob'] / total_implied
                mkt_away_prob = away_odds['implied_prob'] / total_implied

                def edge_bump(od):
                    bump = 0.0
                    for thr, inc in ODDS_EDGE_BUMPS:
                        if od >= thr: bump = inc
                    return bump

                candidates = []

                # evaluate HOME
                if (home_odds['decimal_odds'] <= MAX_DEC_ODDS_TO_BET and
                    home_odds.get('books', 1) >= MIN_BOOKS_REQUIRED and
                    p_home >= MIN_ABS_PROB_TO_BET):                     # model must actually like HOME
                    e = p_home - mkt_home_prob
                    if e >= MIN_EDGE + edge_bump(home_odds['decimal_odds']):
                        candidates.append(('home', p_home, e, home_odds))

                # evaluate AWAY
                if (away_odds['decimal_odds'] <= MAX_DEC_ODDS_TO_BET and
                    away_odds.get('books', 1) >= MIN_BOOKS_REQUIRED and
                    p_away >= MIN_ABS_PROB_TO_BET):                     # model must actually like AWAY
                    e = p_away - mkt_away_prob
                    if e >= MIN_EDGE + edge_bump(away_odds['decimal_odds']):
                        candidates.append(('away', p_away, e, away_odds))

                if not candidates:
                    continue

                # take the larger edge among qualified sides
                bet_team, win_prob, edge, odds_obj = max(candidates, key=lambda t: t[2])
                odds_value = odds_obj['decimal_odds']
                won = (game['home_win'] == 1) if bet_team == 'home' else (game['home_win'] == 0)

                # Conservative Kelly
                kelly_size = self.kelly_bet_size(win_prob, odds_value)
                bet_size = min(
                    MAX_BET_PCT * bankroll,
                    kelly_size * bankroll * KELLY_FRACTION,
                    30.0  # tighter cap; you had 50
                )

                    
                # Place bet
                if won:
                    profit = bet_size * (odds_value - 1.0)
                    wins += 1
                else:
                    profit = -bet_size
                
                bankroll += profit
                pnl += profit
                bets += 1
                
                bet_log.append({
                    'game_date': game['game_date'],
                    'matchup': f"{game['away_team']} @ {game['home_team']}",
                    'bet_team': bet_team,
                    'bet_size': bet_size,
                    'odds': odds_value,
                    'edge': max_edge,
                    'confidence': confidence,
                    'won': won,
                    'profit': profit
                })
        
            # Display results
            if bets > 0:
                win_rate = wins / bets
                roi = (pnl / (bets * (MAX_BET_PCT * initial_bankroll))) * 100
                
                print("\nREALISTIC Backtest Results (with real odds):")
                print(f"  Games with odds: {len(game_odds_processed)}")
                print(f"  Bets placed: {bets}")
                print(f"  Win rate: {win_rate:.1%}")
                print(f"  Total P&L: ${pnl:.2f}")
                print(f"  ROI per bet: {roi:.1f}%")
                print(f"  Final bankroll: ${bankroll:.2f}")
                
                if roi > 15:
                    print("  ⚠️ Still high - check for overfitting")
                elif roi > 5:
                    print("  ✅ Promising results")
                elif roi > 0:
                    print("  📊 Small positive edge")
                else:
                    print("  ❌ Losing strategy")
                
                # Show sample bets
                if bet_log:
                    print(f"\nSample bets:")
                    for bet in bet_log[:5]:
                        result = "WIN" if bet['won'] else "LOSS"
                        print(f"  {bet['game_date'][:10]} {bet['matchup'][:35]:<35} "
                                f"{bet['bet_team'].upper():<4} @{bet['odds']:.2f} "
                                f"${bet['bet_size']:.0f} {result}")
            else:
                print("No qualifying bets found with current parameters")
                print(f"Try reducing MIN_EDGE ({MIN_EDGE}) or MIN_CONF ({MIN_CONF})")

    def _to_decimal_odds(self, odds_value):
        """Convert various odds formats to decimal"""
        try:
            odds = float(odds_value)
            
            # If already decimal (between 1.01 and 50)
            if 1.01 <= odds <= 50:
                return odds
            
            # American odds
            if odds >= 100:
                return 1 + (odds / 100)
            elif odds <= -100:
                return 1 + (100 / abs(odds))
            else:
                return 1.91  # Default -110
                
        except:
            return 1.91  # Default fallback

    def kelly_bet_size(self, win_prob, decimal_odds):
        """Calculate Kelly Criterion bet size"""
        if win_prob <= 0 or decimal_odds <= 1:
            return 0
        
        b = decimal_odds - 1  # Net odds
        p = win_prob
        q = 1 - win_prob
        
        if p * b > q:
            return (p * b - q) / b
        return 0

    def generate_confidence_score(self, prob):
        """Generate confidence score based on probability distance from 0.5"""
        distance = abs(prob - 0.5)
        return min(0.95, max(0.5, 0.5 + 1.6 * distance))

    def backtest_realistic(self, df):
        """Fallback backtest with simulated odds (original method)"""
        print("\nRunning fallback backtest with -110 odds...")
        
        d = df.sort_values('game_date').reset_index(drop=True)
        test_start = int(len(d)*0.8)
        dtest = d.iloc[test_start:].copy()
        
        bankroll = 1000.0
        bets = wins = 0
        pnl = 0.0
        
        for _, g in dtest.iterrows():
            x = g[self.feature_cols].values.reshape(1, -1)
            if self.uses_scaled: x = self.scaler.transform(x)
            p_home = float(self.best_model.predict_proba(x)[0,1])
            p_away = 1.0 - p_home
            
            # Use -110 odds (1.91 decimal)
            mkt_prob = 0.5238  # Implied prob of -110
            edge_home = p_home - mkt_prob
            edge_away = p_away - mkt_prob
            conf = self.generate_confidence_score(p_home)
            
            if max(edge_home, edge_away) >= MIN_EDGE and conf >= MIN_CONF:
                bet_size = MAX_BET_PCT * bankroll
                if edge_home >= edge_away:
                    won = (g['home_win'] == 1)
                else:
                    won = (g['home_win'] == 0)
                
                profit = bet_size * 0.91 if won else -bet_size  # -110 payout
                bankroll += profit
                pnl += profit
                bets += 1
                wins += (1 if won else 0)
        
        if bets > 0:
            win_rate = wins / bets
            roi = (pnl / (bets * MAX_BET_PCT * 1000)) * 100
            print(f"  Fallback results: {bets} bets, {win_rate:.1%} win rate, {roi:.1f}% ROI")

    def save_model(self):
        os.makedirs(MODEL_DIR, exist_ok=True)
        bundle = {
            'model': self.best_model,
            'scaler': self.scaler,
            'feature_cols': self.feature_cols,
            'feature_importance': self.feature_importance,
            'model_metrics': self.model_metrics,
            'uses_scaled': self.uses_scaled,
            'training_date': datetime.now().isoformat(),
            'model_version': '3.4_with_historical_odds',
            'parameters': {
                'min_edge': MIN_EDGE,
                'max_bet_pct': MAX_BET_PCT,
                'min_confidence': MIN_CONF,
                'price_aggregation': PRICE_AGGREGATION
            }
        }
        path = os.path.join(MODEL_DIR, 'betting_model_fixed.pkl')
        with open(path, 'wb') as f:
            pickle.dump(bundle, f)
        print(f"Enhanced model saved to {path}")


def main():
    print("ENHANCED Betting Model Training with Historical Odds")
    print("="*60)
    
    trainer = FixedBettingTrainer()
    
    try:
        print("Step 1: Building core dataset...")
        df = trainer.build_core_dataset()
        
        print("\nStep 2: Engineering features...")
        df = trainer.engineer_core_features(df)
        
        print("\nStep 3: Training calibrated models...")
        results = trainer.train_calibrated_models(df)
        
        print("\nStep 4: Testing prediction quality...")
        trainer.test_predictions(df)
        
        print("\nStep 5: Running realistic backtest with matched odds...")
        trainer.backtest_with_real_odds(df)
        
        print("\nStep 6: Saving enhanced model...")
        trainer.save_model()
        
        print("\n" + "="*60)
        print("ENHANCED MODEL TRAINING COMPLETE!")
        
        best_model = max(results.items(), key=lambda x: x[1]['betting_score'])[0]
        print(f"\nBest Model: {best_model}")
        print(f"AUC: {results[best_model]['auc']:.3f}")
        print(f"Calibration Error: {results[best_model]['calibration_error']:.3f}")
        print(f"Parameters: MIN_EDGE={MIN_EDGE}, MAX_BET={MAX_BET_PCT}, MIN_CONF={MIN_CONF}")
        
        print("\nNext steps:")
        print("1. If you haven't generated historical odds yet, run: python historical_odds_fetcher.py")
        print("2. Re-run this trainer after generating odds for better backtesting")
        print("3. Test the model with: python core_betting_engine.py")
        
    except Exception as e:
        print(f"Training failed: {e}")
        import traceback
        traceback.print_exc()
    finally:
        trainer.conn.close()


if __name__ == "__main__":
    main()